### PR TITLE
Added favicon from https://favicon.io/emoji-favicons/books

### PR DESCRIPTION
**Pull request by 8ctopus**
- nice books favicon from https://favicon.io/emoji-favicons/books
- prevents the code from running past the file exists check in `public/index.php` because favicon does not exist

https://github.com/akrabat/slim-bookshelf/blob/16984915687943c15caf5c85a7d11d299d03796f/public/index.php#L4-L12

### CODE REVIEW

**Comment by akrabat** [comment]
Needs an attribution at the bottom of the README to comply with the license.

**Comment by 8ctopus** [comment]
Good point, I'm a bit at loss here. Maybe you can give me a hand:

> The [emoji graphics](https://github.com/twitter/twemoji/blob/master/assets/svg/1f4da.svg) are from the open source project [Twemoji](https://twemoji.twitter.com/). The graphics are copyright 2020 Twitter, Inc and other contributors. The graphics are licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). You should review the license before usage in your project.

How should I put it?

**Comment by 8ctopus** [comment]
Would it work, if I just copy paste that exact same line in your opinion?

**Comment by akrabat** [comment]
> Would it works, if I just copy paste that exact same line in your opinion?

Yes. I think that would work in a Credits section at the bottom of the README.

**Review by akrabat — APPROVED** [review]

**Pull request merged**
